name: Build
run-name: >-
  ${{
    (!inputs.build_ksun_stable && !inputs.build_ksun_dev) && 'Build plain kernel'
    || (inputs.build_ksun_stable && !inputs.build_ksun_dev) && 'Build kernel & integrate `stable` KernelSU Next via Kprobes'
    || (!inputs.build_ksun_stable && inputs.build_ksun_dev) && 'Build kernel & integrate `dev` KernelSU Next via Kprobes'
    || 'Build kernel & integrate KernelSU Next via Kprobes'
  }}

on:
  workflow_dispatch:
    inputs:
      build_ksun_stable:
        description: "Integrate KernelSU Next: stable"
        required: true
        type: boolean
        default: true
      build_ksun_dev:
        description: "Integrate KernelSU Next: dev"
        required: true
        type: boolean
        default: false

jobs:
  build-ksun-stable:
    if: inputs.build_ksun_stable

    runs-on: ubuntu-latest
    steps:
      - name: Clone source
        uses: actions/checkout@v4
        with:
          ref: android13-5.15
          fetch-depth: '1'

      - name: Set up the toolchain
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            bc bison build-essential curl flex \
            g++-multilib gcc-multilib git gnupg \
            lib32readline-dev lib32z1-dev \
            libelf-dev liblz4-tool libssl-dev \
            lzop zlib1g-dev pahole dwarves cpio zip \
            python3 python-is-python3 tar perl lz4 jq

          # The AOSP Clang version currently in use is r584948
          curl -sSfL --retry 3 --connect-timeout 10 \
            -o clang.tar.gz \
            "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/mirror-goog-main-llvm-toolchain-source/clang-r584948.tar.gz" || \
            { echo "ERROR: Failed to download AOSP Clang! Aborting."; exit 1; }
          mkdir clang-toolchain
          tar -xf clang.tar.gz -C clang-toolchain
          rm clang.tar.gz

      - name: Integrate KernelSU Next
        id: ksun
        shell: bash
        run: |
          (curl -sSfL --retry 3 --connect-timeout 5 \
            "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/stable/kernel/setup.sh" || \
            { echo "ERROR: Failed to retrieve the KernelSU Next setup script! Aborting." >&2; exit 1; }) | \
            bash -s stable

          # Filename will include the release tag, since the stable branch normally updates prior to a new release

          # Determine latest tag for stable releases
          KSU_ID="$(git -C KernelSU-Next tag --list 'v*.[0-9]' --sort=-v:refname | head -1)"

          echo "ksun_id=$KSU_ID" >> "$GITHUB_OUTPUT"

      - name: Set up swap space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 24

      - name: Compute build metadata
        id: meta
        shell: bash
        run: |
          echo "kernel_version=$(make kernelversion | awk '/^[0-9]/ {print $1}')" >> "$GITHUB_OUTPUT"
          echo "date=$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"
          
      - name: Apply custom kernel patch
        run: |
          echo "Applying 001.GKI-below-6.12-fix_sysvipc_kabi_6_7_8 patch..."
          patch -p1 < patches/001.GKI-below-6.12-fix_sysvipc_kabi_6_7_8.patch

      - name: Compile the kernel
        run: |
          # Add AOSP Clang to local PATH
          export PATH="$GITHUB_WORKSPACE/clang-toolchain/bin:$PATH"

          # Generate configuration
          make -j"$(nproc --all)" O=out ARCH=arm64 CC=clang LD=ld.lld LLVM=1 LLVM_IAS=1 gki_defconfig

          # Run make
          make -j"$(nproc --all)" O=out ARCH=arm64 CC=clang LD=ld.lld LLVM=1 LLVM_IAS=1

      - name: Package image with AnyKernel3  # Avoid zipping, as `upload-artifact` handles compression automatically
        run: |
          cp .github/goodies/AnyKernel3.zip .
          unzip AnyKernel3.zip -d AnyKernel3/
          cp out/arch/arm64/boot/Image.gz AnyKernel3/

      - name: Upload the flashable kernel
        uses: actions/upload-artifact@v4
        with:
          name: >-
            common-${{ steps.meta.outputs.kernel_version }}_ksun-stable-${{ steps.ksun.outputs.ksun_id }}-kprobes_${{ steps.meta.outputs.date }}
          path: AnyKernel3/

  build-ksun-dev:
    if: inputs.build_ksun_dev

    runs-on: ubuntu-latest
    steps:
      - name: Clone source
        uses: actions/checkout@v4
        with:
          ref: android13-5.15
          fetch-depth: '1'

      - name: Set up the toolchain
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            bc bison build-essential curl flex \
            g++-multilib gcc-multilib git gnupg \
            lib32readline-dev lib32z1-dev \
            libelf-dev liblz4-tool libssl-dev \
            lzop zlib1g-dev pahole dwarves cpio zip \
            python3 python-is-python3 tar perl lz4 jq

          # The AOSP Clang version currently in use is r584948
          curl -sSfL --retry 3 --connect-timeout 10 \
            -o clang.tar.gz \
            "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/mirror-goog-main-llvm-toolchain-source/clang-r584948.tar.gz" || \
            { echo "ERROR: Failed to download AOSP Clang! Aborting."; exit 1; }
          mkdir clang-toolchain
          tar -xf clang.tar.gz -C clang-toolchain
          rm clang.tar.gz

      - name: Integrate KernelSU Next
        id: ksun
        shell: bash
        run: |
          (curl -sSfL --retry 3 --connect-timeout 5 \
            "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/dev/kernel/setup.sh" || \
            { echo "ERROR: Failed to retrieve the KernelSU Next setup script! Aborting." >&2; exit 1; }) | \
            bash -s dev

          # Filename will include the current version number instead of the tag
          # This simplifies tracking for the dev branch builds, as tags only update on new releases

          # Calculate the version of KernelSU Next by counting the commits
          COMMIT_VALUE="$(git -C KernelSU-Next rev-list --count HEAD)"
          KSU_ID="$((30000 + ${COMMIT_VALUE:-0}))"

          echo "ksun_id=$KSU_ID" >> "$GITHUB_OUTPUT"

      - name: Set up swap space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 24

      - name: Compute build metadata
        id: meta
        shell: bash
        run: |
          echo "kernel_version=$(make kernelversion | awk '/^[0-9]/ {print $1}')" >> "$GITHUB_OUTPUT"
          echo "date=$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"

      - name: Compile the kernel
        run: |
          # Add AOSP Clang to local PATH
          export PATH="$GITHUB_WORKSPACE/clang-toolchain/bin:$PATH"

          # Generate configuration
          make -j"$(nproc --all)" O=out ARCH=arm64 CC=clang LD=ld.lld LLVM=1 LLVM_IAS=1 gki_defconfig

          # Run make
          make -j"$(nproc --all)" O=out ARCH=arm64 CC=clang LD=ld.lld LLVM=1 LLVM_IAS=1

      - name: Package image with AnyKernel3  # Avoid zipping, as `upload-artifact` handles compression automatically
        run: |
          cp .github/goodies/AnyKernel3.zip .
          unzip AnyKernel3.zip -d AnyKernel3/
          cp out/arch/arm64/boot/Image.gz AnyKernel3/

      - name: Upload the flashable kernel
        uses: actions/upload-artifact@v4
        with:
          name: >-
            common-${{ steps.meta.outputs.kernel_version }}_ksun-dev-${{ steps.ksun.outputs.ksun_id }}-kprobes_${{ steps.meta.outputs.date }}
          path: AnyKernel3/

  # If nothing is checked, proceed to build the plain kernel
  build-plain:
    if: ${{ !inputs.build_ksun_stable && !inputs.build_ksun_dev }}
    runs-on: ubuntu-latest

    steps:
      - name: Clone source
        uses: actions/checkout@v4
        with:
          ref: android13-5.15
          fetch-depth: '1'

      - name: Set up the toolchain
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            bc bison build-essential curl flex \
            g++-multilib gcc-multilib git gnupg \
            lib32readline-dev lib32z1-dev \
            libelf-dev liblz4-tool libssl-dev \
            lzop zlib1g-dev pahole dwarves cpio zip \
            python3 python-is-python3 tar perl lz4 jq

          # The AOSP Clang version currently in use is r584948
          curl -sSfL --retry 3 --connect-timeout 10 \
            -o clang.tar.gz \
            "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/mirror-goog-main-llvm-toolchain-source/clang-r584948.tar.gz" || \
            { echo "ERROR: Failed to download AOSP Clang! Aborting."; exit 1; }
          mkdir clang-toolchain
          tar -xf clang.tar.gz -C clang-toolchain
          rm clang.tar.gz

      - name: Set up swap space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 24

      - name: Compute build metadata
        id: meta
        shell: bash
        run: |
          echo "kernel_version=$(make kernelversion | awk '/^[0-9]/ {print $1}')" >> "$GITHUB_OUTPUT"
          echo "date=$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"  

      - name: Compile the kernel
        run: |
          # Add AOSP Clang to local PATH
          export PATH="$GITHUB_WORKSPACE/clang-toolchain/bin:$PATH"

          # Generate configuration
          make -j"$(nproc --all)" O=out ARCH=arm64 CC=clang LD=ld.lld LLVM=1 LLVM_IAS=1 gki_defconfig

          # Run make
          make -j"$(nproc --all)" O=out ARCH=arm64 CC=clang LD=ld.lld LLVM=1 LLVM_IAS=1

      - name: Package image with AnyKernel3  # Avoid zipping, as `upload-artifact` handles compression automatically
        run: |
          cp .github/goodies/AnyKernel3.zip .
          unzip AnyKernel3.zip -d AnyKernel3/
          cp out/arch/arm64/boot/Image.gz AnyKernel3/

      - name: Upload the flashable kernel
        uses: actions/upload-artifact@v4
        with:
          name: common-${{ steps.meta.outputs.kernel_version }}_${{ steps.meta.outputs.date }}
          path: AnyKernel3/
